language: node_js
node_js:
- '6'
- 6.3.0
- '4'
- 4.4.7
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3.10.3
after_script:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- "./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info"
- snyk auth $SNYK_TOKEN && snyk monitor --org=smockle
env:
  global:
  - secure: hrkVaZCenH331e4LEy8sygnqFv8FsQf17K5JJ565dF6XjbkgSbl23FPw99Fy3iD2/E2dndvpbP9/QQtkyyeOs1bkMr02tJ3OoPv2in64IVbNIgD0+eQPImCrhTn7ORu5vTaKJ7Ema3qDDmUZ6pnJbnCjeuykquFsELzU1Iip2d7g/dRmRWoILkzF7vdn0Bbm0WM/harQplbzL9b7O5dZIz7QC+wqOtCMPJEWZ0F8P5qFPnBYBk+xoPW95Ob2Lb0Pmt+WYnxpNHl8/Cwwa3O2E5oLjict9VZZ2l+pAJL5yk2Vz87fjrCrGv7GWtWwwLrYOvoZiDoSO93WPXydqlsnsExpx44Y/IORGgTcEsHCv/fFIVx/Z0A+8o68LQEIzYH3PaKIqay6nYLsFVE7j3wT+Xd3+GF1YRsB3BwltyepZwCeIW5NqB8tkBDJw4ROjbYHI8tXwoVEsatowmIeys8m/G9Q9kP8PQz9A9K/00mwCg/5RLQEUqXOjtsaMAJStjFhUewGqFmV6IrQZoEJTuCQiFkdTjvs5Uw/wzXqzOGe4vOH3EDtPg0Xpm5AK9hcN+WXGbaDRsf+9MYaQGAJz2uIzXbUHoBnyz19bxP8NW8yX2BIBjXqgD5Tu2jNcUNcRfott4fwE5H8tGODhYvc9UgQD1LwfKdRRkduWe9ILUM5Ous=
  - secure: XtK6XBeKLHO87iUDGLF017UL7UeQtbduo/jl4JOvxLnalN9MpGiV5IbrHENRbp/0IewOJSH73qTnZ1q6XqBPlOXw3hMHVfHFeRB/HIJISa4kPcHCh1GNNGQYAORSHrKEEHOLUwKp5HlfeQhmqkK501+6KXXOR5O/h0GA1Obzk6Nmd6hWI2S5DDbx1J+Me8kHNMBz+thvaL/R0lnT6IK5w/OM6TQH9jfmWbuuWz9j8MdkK7QXAAdXi/av36S8w0A/KB0l+vxhAhbU2YSUlAyhyCDXTN/7xApeuJqT6NvYkePm6VLNNzw802+b0mRoR+WGIS4cjYeKqlsI8tl9/8Ep1FxgkObsGxdGyOHjs1ouymToQOgM2k7yphcAR8mVoPTz5kKLvNboHpRcBYg/IjaIxDET3CpON3MSO7JCRS/SNVfBmPVEXyoQj/XPvAvTAA0ilaGcpNDQUJm190c0QiM05FV0DtGfbPLqkyZpmMQMxqUs197ELzyHUDGrXDJhJiVLN2+K4eGf42CFlKsD+Nssz8OymSgbuJ0jM3igGRHCRiL7EGREw05qNPFau3YprZ8BZ3UDMCoUoDwSz0QqeG+IWcp/SIwE8IlsTWhadrIqe5zS9BoFwLstYvILDox3gq0whXzdxNkxigR5hqHGybBBpL4S+5dHfsUgk9qDOz75U8I=
  - secure: oQhRMXJWjvdaP5i5YATN2d5xfLL6k/84bxsq6W6/RybDk7UdY9jgNOrooPdnmMOr06TEBoB2mWC7wm4ZANLHWLPB7weW5GYGSQr/K0Mf4u5dRpDkZKFBwmrlVelpXOSwY+zO6REAbIS9CChMVRrRStIshQQg4B5SQPhgqlKQ4Bx/nwGwKH4+mW5nK3MSfa0M/h607HpCDfeNQLug2kpgXYfT6bbI3ExUhUehKnArs48FxAnmhgwC+HczhaqIiatxlfEvWzBR+a/aY44WnjQHWUPNS1ilgEENFdRn0+h6K4h89eUK118ZpbzyHvP9mO2CmBU9VMhZVnY5xHNa4KbIxKQgtV1Qf4AWVZ7DEigm1HHmtvdeoXBeLLJo2PtPRP1TY3G5Xs1IbRzZGKV5cqLqh1Swtr3Y75eXL5gH4Sz1+d7fK2hPAQrs8jWom65etdrjn2aZAswQGwISCRleVIFBBjeUDJh7muf6lJlHCFvz72opUGNb8g76vRqrVgJ4qoNJ4EwWwKNbFeRkv3FYsZa9laFKpzSOMTbRAXO0llZAoWtIWqOZsmvIeqsSef9YZSzGY90f8qP/EQnmwNGmKcoZCDtUHpkBIQnFio8j5NUtYYwcHsD7eQ0QQAxNwkqYpmk/3I5ggXtunXeIgu+vsFX/T0Grt++sjaNJGO/QMeRiDNQ=
