language: node_js
node_js:
- '6'
- 6.2.2
- '4'
- 4.4.7
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3.9.5
after_script:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- "./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info"
- snyk auth $SNYK_TOKEN && snyk monitor
env:
  global:
