language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
- npm run coverage
- npm run codeclimate
env:
  global:
  - secure: mdLYZUqYgCFlX3yligkupE+tEsZH4mVSxvIARV5jpdr5BJM3Le9HTLs0iVG71Er1A8amOYbcvDaZyunvtnSYeRgmpMOJkY0/xkYldFO/5dH38hkWT/ZROabEsEK+broNtwK2RIJEVKGhpu0lLWrmv/uD+ZrlvyzbtkHEukorFLHuSVpEu3ZSu3imL1Lo/yOovtzDTZTMHZXvaVgJwK7Nb0GyzQPqokLrDhe0cXxV9/MuekDk/ET9tw+g+K6yeXbklArPPUTZ75NSTE2r02XVNcktM/C0QF8zT0JNBwCSk9ne7WfSCAPXDHXxERD52LtBUfHfSEqyR6vWvh98lfHmI0BF6Z8i67LNdr9McvX3PbiFRzvClcR3bzaJLPdCiInZvbIWRYyfyvYoT9S64Z4EnsbOh2bUzDyxF03+KbO9dmiCPlD3Aa70IEL8Y4ylRvdBAlnuzbrSzvbFNelCrNKfLPGY79TzBqiKzLwbRhdagOjwbvGnC1kAQYwm8dZCQwWKiwBUdlSyh3f7Kmf3tiorKaiWGjWvhQQJycSVDKe8UTjKbIRK7ZEhDL+ZpbpRviiBRCB0dLMbvuVdwo2138O0VOWWUzRtx9QNSW0Crr7/MQkXmOLUZd18Oi/U4xkSEiqWc8MMdYHJOMCtE+23o4gplRJYDJcFszKsWHNepjfTYVA=
  - secure: NWsEQyPx6mgrl+Q6k9iYd8V+xUSuzYJLi5nN8K3YNjx5/lzxNliCY89dGQ/sUZy3I2dtiQb61Cno6Ki7de2Q2yWSCZJK7w1x0B8zk2tb1J/Gyy4G4HFhjeWPyJQ61BiH+vu3zpA+Ad+/faR/pBegPd43gQ7qGbOldj2jikQ4T3qo+0c0yAcu0lveEmgB6CrvFf/TojI2BTPD9ez8rlJlTVUMhqm8j0Kly48mdchx08E8BTTHDx0I9UceuTxuy8HyKbL0wOARf6tsTiBVbKdie/qDwu3NUP0mGJ7Xt0C9/YLfuhP7e+cORzT+JWQuRREZys/x+xX43ckDS5HLq09Aeodc85toSD3CIWjNNE9hKr91EjmysIqvzFmZ0ElyDXjHKLrmfcedI2TAajuY0pycDD6zC/eddDIl8jhsbYKEZfArO763aM5hXHdxviJpmsdIBU2A297MrG4LzRZW6kUkO8rUaXqBzNiafICrOskF6hE91qIiJGd8an4i7zeBfnb3q1S4BVBzBj7DiH6p+Ud5PJkASOhj/7O5Qamg6LSDaEkzaYN4QL+z8rvCVthaWtJFpxVAa8RL7xrfMY9nwtPClbgwz28RS7dHrqZiDZA8a6UPbkGLLo9w2Gmlti0I5XJtc5gkWOQU9pVKYwXpEKi0rWNtFTbAmh++NSn+Givtsrs=
