language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
after_script:
- npm run coverage
- npm run codeclimate
env:
  global:
    secure: mdLYZUqYgCFlX3yligkupE+tEsZH4mVSxvIARV5jpdr5BJM3Le9HTLs0iVG71Er1A8amOYbcvDaZyunvtnSYeRgmpMOJkY0/xkYldFO/5dH38hkWT/ZROabEsEK+broNtwK2RIJEVKGhpu0lLWrmv/uD+ZrlvyzbtkHEukorFLHuSVpEu3ZSu3imL1Lo/yOovtzDTZTMHZXvaVgJwK7Nb0GyzQPqokLrDhe0cXxV9/MuekDk/ET9tw+g+K6yeXbklArPPUTZ75NSTE2r02XVNcktM/C0QF8zT0JNBwCSk9ne7WfSCAPXDHXxERD52LtBUfHfSEqyR6vWvh98lfHmI0BF6Z8i67LNdr9McvX3PbiFRzvClcR3bzaJLPdCiInZvbIWRYyfyvYoT9S64Z4EnsbOh2bUzDyxF03+KbO9dmiCPlD3Aa70IEL8Y4ylRvdBAlnuzbrSzvbFNelCrNKfLPGY79TzBqiKzLwbRhdagOjwbvGnC1kAQYwm8dZCQwWKiwBUdlSyh3f7Kmf3tiorKaiWGjWvhQQJycSVDKe8UTjKbIRK7ZEhDL+ZpbpRviiBRCB0dLMbvuVdwo2138O0VOWWUzRtx9QNSW0Crr7/MQkXmOLUZd18Oi/U4xkSEiqWc8MMdYHJOMCtE+23o4gplRJYDJcFszKsWHNepjfTYVA=
