// flow-typed signature: e3ebcaf1f41a2eac82dc69fe416636e2
// flow-typed version: <<STUB>>/colortape_v^0.1.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'colortape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'colortape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'colortape/test/fixtures/error' {
  declare module.exports: any;
}

declare module 'colortape/test/fixtures/failure' {
  declare module.exports: any;
}

declare module 'colortape/test/fixtures/success' {
  declare module.exports: any;
}

declare module 'colortape/test/index' {
  declare module.exports: any;
}

declare module 'colortape/test/pipe' {
  declare module.exports: any;
}

declare module 'colortape/test/unit' {
  declare module.exports: any;
}

declare module 'colortape/test/wrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'colortape/index' {
  declare module.exports: $Exports<'colortape'>;
}
declare module 'colortape/index.js' {
  declare module.exports: $Exports<'colortape'>;
}
declare module 'colortape/test/fixtures/error.js' {
  declare module.exports: $Exports<'colortape/test/fixtures/error'>;
}
declare module 'colortape/test/fixtures/failure.js' {
  declare module.exports: $Exports<'colortape/test/fixtures/failure'>;
}
declare module 'colortape/test/fixtures/success.js' {
  declare module.exports: $Exports<'colortape/test/fixtures/success'>;
}
declare module 'colortape/test/index.js' {
  declare module.exports: $Exports<'colortape/test/index'>;
}
declare module 'colortape/test/pipe.js' {
  declare module.exports: $Exports<'colortape/test/pipe'>;
}
declare module 'colortape/test/unit.js' {
  declare module.exports: $Exports<'colortape/test/unit'>;
}
declare module 'colortape/test/wrap.js' {
  declare module.exports: $Exports<'colortape/test/wrap'>;
}
