// flow-typed signature: 1a1a5f7378a3eb94c91b140831760eab
// flow-typed version: <<STUB>>/@std/esm_v^0.5.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@std/esm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@std/esm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@std/esm/index' {
  declare module.exports: $Exports<'@std/esm'>;
}
declare module '@std/esm/index.js' {
  declare module.exports: $Exports<'@std/esm'>;
}
